Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.box_version = "3.1.16"    
  config.vm.hostname = "db01"
  config.vm.network "private_network", ip:"192.168.56.4"
  config.vm.network "forwarded_port", guest:3306, host:3306
  config.vm.provision "shell", path:"provision.sh"
end
